name: simple_notes_app
description: Simple notes app with Appwrite

version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  appwrite: ^9.0.0
  equatable: ^2.0.5
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  formz: ^0.6.0
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  go_router: ^6.5.3
  hydrated_bloc: ^9.1.0
  json_annotation: ^4.8.0
  lottie: ^2.3.2
  path_provider: ^2.0.13
  shared_preferences: ^2.1.0
  timeago: ^3.4.0
  uuid: ^3.0.7
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/

import_sorter:
  emojis: true